apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 2379
    targetPort: 2379
  selector:
    component: etcd
