# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/loki"  # Ensure this path exists on your node
  persistentVolumeReclaimPolicy: Retain


# pv-metadata-collector.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: metadata-collector-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/metadata-collector"
  persistentVolumeReclaimPolicy: Retain
---
# pv-data-processor.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-processor-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-processor"
  persistentVolumeReclaimPolicy: Retain


