apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-collector
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metadata-collector
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "namespaces", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "volumeattachments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metadata-collector
subjects:
- kind: ServiceAccount
  name: metadata-collector
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: metadata-collector
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-collector-pvc
  namespace: monitoring
spec:
  volumeName: metadata-collector-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-collector
  namespace: monitoring
  labels:
    app: metadata-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-collector
  template:
    metadata:
      labels:
        app: metadata-collector
    spec:
      serviceAccountName: metadata-collector
      containers:
      - name: metadata-collector
        image: freshinit/metadata-collector:latest
        imagePullPolicy: Always
        env:
        - name: COLLECTION_INTERVAL
          value: "300"
        - name: OUTPUT_DIR
          value: "/data"
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: metadata-collector-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-collector
  namespace: monitoring
  labels:
    app: metadata-collector
spec:
  ports:
  - port: 8000
    targetPort: 8000
    name: metrics
  selector:
    app: metadata-collector
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metadata-collector
  namespace: monitoring
  labels:
    app: metadata-collector
spec:
  selector:
    matchLabels:
      app: metadata-collector
  endpoints:
  - port: metrics
    interval: "30s"
