apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log metadata changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: "" # core API group
      resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims", "persistentvolumes"]
    - group: "apps"
      resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    - group: "batch"
      resources: ["jobs", "cronjobs"]
    - group: "autoscaling"
      resources: ["horizontalpodautoscalers"]
    - group: "networking.k8s.io"
      resources: ["ingresses", "networkpolicies"]
    - group: "storage.k8s.io"
      resources: ["storageclasses", "volumeattachments"]
    verbs: ["create", "update", "patch", "delete"]
  
  # Log etcd access at Metadata level
  - level: Metadata
    resources:
    - group: ""
      resources: ["endpoints"]
    
  # Log pod changes related to lifecycle at RequestResponse level
  - level: RequestResponse
    resources:
    - group: "" # core API group
      resources: ["pods/status"]
    
  # Log everything else at Metadata level
  - level: Metadata
    omitStages:
      - "RequestReceived"
